version: '3.3'

services:
  service:
    container_name: 'service-mini-note'
    build: .
    ports:
      - '9077:9077'
    volumes:
      - ./src:/app
    restart: on-failure
    depends_on:
      - mongo

  mongo:
    image: 'mongo:6.0'
    container_name: 'service-mini-note-mongo'
    ports:
      - '27297:27017'
    volumes:
      - ./mongodb:/data/db
    restart: unless-stopped

networks:
  default:
    external:
      name: mini_note_network